### ISSUE TITLE
Remember Me forgets

### ISSUE THREAD

**Issue by wandored** [wandored/cadashboard#125]
the remember me button on the login page doesn't work.

**Comment by wandored** [comment]
would like it to remember for at least a week

**Comment by JKinsella04** [comment]
The code was not creating the cookie but it wasn't a failure in the cookie creation functionality it seemed to just be a problem with the html code not taking the input from the page and passing it to the rest of the dashboard. It now stores the input and allows for the cookie to be created.
The file with the error was [cadashboard\dashapp\templates\security\login_user.html](https://github.com/wandored/cadashboard/blob/9d8b91ab4175eb72e3942003031ec0dbaa808a04/dashapp/templates/security/login_user.html#L48)
Old code
```html
<div class="form-check form-switch d-flex align-items-center mb-3">
    <input class="form-check-input" type="checkbox" id="rememberMe">
    <label class="form-check-label mb-0 ms-2" for="rememberMe">Remember me</label>
</div>
```
New code
```html
<div class="form-check d-flex mb-3">
   {{ login_user_form.remember() }}
   <label class="form-check-label mb-0 ms-2" for="rememberMe">Remember Me </label>
</div>
```

**Comment by wandored** [comment]
Are you doing your code edits directly on the test server?  I went into
update it because for some reason it's not pulling data past the 4th.
